name: Rename __main__.py for Deployment

on:
  push:
    branches:
      - main

jobs:
  rename-main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Find and copy __main__.py files
        run: |
          find . -type f -name '__main__.py' | while read file; do
            dir=$(dirname "$file")
            cp "$file" "$dir/main__.py"
          done

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run deploy
